version: '3'

services:
  # postgres db
  db:
    build: ./db
    networks:
      - core

  # node express backend - exposes data from db
  apparel:
    build: ./apparel
    volumes:
      - ./apparel:/app
    depends_on:
      - db
    ports:
      - 5001:80
    networks:
      - core

  # python Flask backend - exposes data with prices
  prices:
    build: ./prices
    volumes:
      - ./prices:/app
    ports:
      - 5002:80
    depends_on:
      - apparel
    networks:
      - core
      - site

  # php frontend - presents data with prices
  site:
    build: ./site
    volumes:
      - ./site:/src
    ports:
      - 5000:80
    depends_on:
      - prices
    networks:
      - site

networks:
  core:
    driver: bridge
  site:
    driver: bridge

## WHEN using postgres > 9.6.16 ##
#  secure-db:
#    build: ./db
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=d4REn0LdCH4B